Repository nobl9/sloctl, pull requests merged in 2024-07, with the labels that each got.

#158 fix: Remove replace clause
  .golangci.yml
  go.mod
  go.sum
  internal/printer/printer.go
  internal/replay.go
Labels: bug, patch, go

#159 chore: Correct string replacement in Docker e2e tests
  test/dockertest/docker_test.go
Labels: chore, patch, go

#166 chore: Update VERSION
  internal/VERSION
Labels: chore, patch

#161 chore: Update Readme
  README.md
Labels: chore, patch

#175 chore: Update docker image to 1.22-alpine3.20
  Dockerfile
Labels: chore, patch
