Repository nobl9/sloctl, pull requests merged in 2024-04, with the labels that each got.

#93 chore: Use JSON numbers with updated SDK
  .github/workflows/e2e-tests-dispatch.yml
  go.mod
  go.sum
  internal/root.go
Labels: chore, patch, go

#94 chore: Update module github.com/nobl9/nobl9-go to v0.79.3-rc1
  go.mod
  go.sum
Labels: chore, patch, go

#98 feat: PC-12282 Introduce metadata annotations
  go.mod
  test/get.bats
  test/inputs/get/alertpolicies.yaml
  test/inputs/get/projects.yaml
  test/inputs/get/services.yaml
  test/inputs/get/slos.yaml
  test/outputs/get/alertpolicy.yaml
Labels: enhancement, go, minor

#101 chore: Bump version to 0.1.0
  internal/VERSION
Labels: chore, patch

#102 chore: Pin yq version for tests
  test/docker/Dockerfile.e2e
  test/docker/Dockerfile.unit
Labels: chore, patch

#103 chore: Fix goreleaser marking pre-releases as latest
  .goreleaser.yml
Labels: chore, patch

#105 chore: Remove management approval release step
  .github/workflows/release.yml
Labels: chore, patch
