Repository nobl9/sloctl, pull requests merged in 2024-06, with the labels that each got.

#133 chore: Bump VERSION file for release 0.2.1
  internal/VERSION
Labels: chore, patch

#134 chore: Bump version for release
  internal/VERSION
Labels: chore, patch

#137 fix: Switch to distroless image in Dockerfile [PC-13119]
  Dockerfile
  cspell.yaml
Labels: bug, patch

#138 chore: change folder to directory in brews Goreleaser config
  .goreleaser.yml
Labels: chore, patch

#144 chore: Adjust e2e tests for createdAt and createdBy new v1alpha Project.Spec fields
  test/test_helper/load.bash
Labels: chore, patch

#153 fix: Correct double quoted JSON string literals handling
  go.mod
  go.sum
Labels: bug, patch, go

#154 chore: Trim prefix from Docker image in Docker tests
  test/dockertest/docker_test.go
Labels: chore, patch, go
