Repository nobl9/sloctl, pull requests merged in 2024-11, with the labels that each got.

#242 fix: Fix string display
  internal/replay_delete.go
Labels: bug, patch, go

#237 chore: Queue/Trigger the replay using sloctl [PC-13394]
  internal/replay.go
  internal/replay_delete.go
  internal/replay_list.go
Labels: chore, patch, go, passed-testing

#248 chore: Bump version to 0.7.0 for release
  internal/VERSION
Labels: chore, patch
