Repository nobl9/sloctl, pull requests merged in 2024-03, with the labels that each got.

#68 chore: Introduce SOC-2 compliant release process
  .github/workflows/e2e-tests.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: chore, patch

#69 doc: Update DEVELOPMENT.md
  docs/DEVELOPMENT.md
Labels: documentation

#70 chore: Update release.yml
  .github/workflows/release.yml
Labels: chore, patch

#72 chore: Update release.yml
  .github/workflows/release.yml
Labels: chore, patch

#76 chore: Update Nobl9 logo
  README.md
Labels: chore, patch

#80 chore: Fix README.md logo
  README.md
Labels: chore, patch

#81 chore: enhance CI workflow for multi-registry Docker image pushes
  .github/workflows/release.yml
Labels: chore, patch

#89 fix: Distinct between float and integer when printing YAML format
  .golangci.yml
  Makefile
  go.mod
  go.sum
  internal/printer/printer.go
  test/docker/Dockerfile.e2e
  test/docker/Dockerfile.unit
  test/get.bats
  test/inputs/get/agent.yaml
  test/inputs/get/alertpolicies.yaml
  test/inputs/get/directs.yaml
  test/outputs/get/alertpolicy.yaml
  test/outputs/get/direct.yaml
Labels: bug, patch, go

#88 chore: Set default version from VERSION file
  internal/VERSION
  internal/root.go
  internal/version.go
Labels: chore, patch, go

#91 chore: Correct VERSION file to have proper semver
  internal/VERSION
Labels: chore, patch

#83 feat: PC-11745 Add primary objective sloctl support
  test/inputs/get/slos.yaml
Labels: enhancement, go, minor
