Repository nobl9/sloctl, pull requests merged in 2024-10, with the labels that each got.

#222 chore: Update gofmt usage
  Makefile
  cspell.yaml
Labels: chore, patch

#223 chore: Update module github.com/nobl9/nobl9-go to v0.86.0
  go.mod
  go.sum
Labels: chore, patch, go

#213 feat: PC-14184 Add sourceSLO field in replay config file
  go.mod
  go.sum
  internal/replay.go
Labels: enhancement, go, minor

#227 chore: Bump version file to 0.6.0
  internal/VERSION
  internal/replay_example.sh
Labels: chore, patch

#232 feat: List the queued replays [PC-13341]
  internal/replay.go
  internal/replay_list.go
Labels: enhancement, go, minor, passed-testing
