Repository nobl9/sloctl, pull requests merged in 2024-08, with the labels that each got.

#176 fix: Add missing stderr from assert_success output
  test/apply-and-delete.bats
  test/aws-iam-ids.bats
  test/delete-by-name.bats
  test/get.bats
  test/test_helper/load.bash
Labels: bug, patch

#177 feat: Improve flags handling [PC-13534]
  .github/workflows/e2e-tests-dispatch.yml
  internal/apply.go
  internal/aws_iam_ids.go
  internal/config.go
  internal/delete.go
  internal/flags.go
  internal/get.go
  internal/replay.go
  internal/root.go
  test/delete-by-name.bats
  test/get.bats
  test/test_helper/load.bash
Labels: enhancement, go, breaking-change, minor, passed-testing

#178 chore: Update goreleaser to v2 and action to v6
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: chore, patch

#184 chore: Adjust release doc
  docs/RELEASE.md
Labels: chore, patch

#186 fix: Bring back get alerts project flags
  internal/flags.go
  internal/get.go
Labels: bug, patch, go, passed-testing

#169 feat: PC-13263 New kind: Reports
  go.mod
  go.sum
  internal/delete.go
  internal/get.go
  test/delete-by-name.bats
  test/get.bats
  test/inputs/delete-by-name/report.yaml
  test/inputs/get/reports.yaml
  test/test_helper/load.bash
Labels: enhancement, go, minor

#188 chore: Update VERSION file
  internal/VERSION
Labels: chore, patch

#193 fix: Add project flag back again for sloctl replay
  internal/apply.go
  internal/delete.go
  internal/flags.go
  internal/get.go
  internal/replay.go
Labels: bug, patch, go, passed-testing

#194 chore: Update VERSION
  internal/VERSION
Labels: chore, patch

#200 fix: Correct sloctl replay help
  internal/replay_example.sh
  internal/root.go
Labels: bug, patch, go
