Repository nobl9/sloctl, pull requests merged in 2025-03, with the labels that each got.

#294 fix: budgetadjutments events - handle multiple YAML documents in one file
  internal/VERSION
  internal/budgetadjustments/events/delete.go
  internal/budgetadjustments/events/inputreader.go
  internal/budgetadjustments/events/inputreader_test.go
  internal/budgetadjustments/events/update.go
Labels: bug, patch, go, passed-testing

#299 fix: version
  internal/VERSION
Labels: bug, patch

#302 chore: Enable token caching for e2e tests
  test/docker/Dockerfile.e2e
Labels: chore, patch

#304 chore: Automate version file control and fix goreleaser
  .goreleaser.yml
  Makefile
  cspell.yaml
  internal/VERSION
  internal/version.go
Labels: chore, patch, go

#306 chore: Fix bats tests
  Makefile
Labels: chore, patch
