Repository nobl9/sloctl, pull requests merged in 2025-05, with the labels that each got.

#324 chore: Do not use sudo for windows in install.bash
  install.bash
Labels: chore, patch

#325 chore: Correct install script executable handling
  install.bash
Labels: chore, patch, go

#331 chore: Expect 16 or 20 chars for agent client_id
  test/get.bats
Labels: chore, patch

#335 chore: switch to JSON cspell config
  cspell.json
  cspell.yaml
  package.json
  scripts/format-cspell-config.js
Labels: chore, patch, javascript

#334 feat: PC-16670 Cancel importing replay
  internal/replay.go
  internal/replay_cancel.go
  internal/replay_delete.go
  internal/replay_errors.go
Labels: enhancement, go, minor, passed-testing
